version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - cd demo
      - mvn clean test package

artifacts:
  files:
    - demo/target/*.jar
    - Procfile
  discard-paths: yes